### ISSUE TITLE
Purple Dev avi font

### ISSUE THREAD

**Issue by spences10** [PurpleDevs/particles-example#1]
@amandeepmittal I'd like to know what font it was you used for the Purple Dvs avatar in use it in this example please 👍 

Don't worry I'll make the changes, adding you to get your attention 😄

**Comment by amandeepmittal** [comment]
@spences10 I used `signpainter` available here: http://abc-font.com/font.php?font=SignPainter-HouseScript

**Comment by amandeepmittal** [comment]
Brad's tutorials are so straightforward to understand. Thanks for the link 👍

**Comment by spences10** [comment]
Is there a cdn for it?

I had a look but couldn't find one

**Comment by amandeepmittal** [comment]
Not on that site. Let me find one for you. I'll get back to you tomorrow.

**Comment by amandeepmittal** [comment]
@spences10 Could not find a CDN for it. Most sites that are offering it claims it is a paid one. Should we change then?

**Comment by spences10** [comment]
@amandeepmittal nah, I got a nice/similar font in the example 👍

**Comment by amandeepmittal** [comment]
@spences10 Yeah, I saw that. I was talking about the logo though.

**Comment by spences10** [comment]
@amandeepmittal @gilsjhonny I guess we should all agree, right?

**Comment by gilsjhonny** [comment]
I really like the logo! I guess I'll use the font for side projects 😆
